coova/coova-chilli

- CREDITS
While here, sort file alphabetically, use 1 space, tabs for separator
modified:   CREDITS
> Add myself to CREDITS file

- src/redir.c
> fix noradallow option

- src/linux/xt_coova.c
hint taken from xt_recent module.
> fix compile error when kernel version >= 3.10

- src/linux/xt_coova.c
> fix xt_coova.c with kernel version >= 3.10.0

- configure.ac
- src/dhcp.c
- src/location.c
> fix compile with --enable-pppoe issue #50

- README
Resolves issue #72
Signed-by: Sevan Janiyan <venture37@geeklan.co.uk>
> Restore symlink from README > README.md

- src/cmdline.mini.c
> Fixes compilation error debug statement already defined

- src/dhcp.c
- src/queue.c
> Fixes compilation error using --netfilter-queue

- conf/functions.in
- configure.ac
- fixed the default configure option for disable_json which caused the json interface to be disabled by default
- added the possibility to use HS_LOCATIONOPT82 to enable locationopt82 support
> fix and enhancement

- src/redir.c
According to my question in #111 , here is my contribution to add it in json
> Add nasid to json replies

- src/chilli.c
- src/chilli_module.c
- src/dhcp.c
- src/ewt.c
- src/garden.c
- src/ippool.c
- src/kcoova.c
- src/main-opt.c
- src/main-proxy.c
- src/main-query.c
- src/main-redir.c
- src/main-response.c
- src/net.c
- src/radius.c
- src/redir.c
- src/rtmon.c
- src/session.c
- src/system.h
- src/tun.c
- src/util.c
Use the implementation of snprintf() supplied by libc.
> Drop the use of safe_snprintf

- configure.ac
- src/Makefile.am
And some dependencies to compile using cURL and netfilter_queue
> Fix dependencies when using cURL and netfilter libraries.

- src/redir.c
From daniel-sullivan issue #136
> FIX: Invalid JSON in chilliJSON.reply

- src/chilli.c
- src/dhcp.c
- src/garden.c
- src/redir.c
- src/system.h
> ARM: should use PRIu64 for uint64_t

- README.md
> Restore instructions on how to get started once repo has been cloned.

- configure.ac
- src/dhcp.c
- src/ippool.c
- src/radius.c
- src/redir.c
Contains fix for build issue #153 and nasty runtime error #106, superfluous checks introduced in https://github.com/coova/coova-chilli/commit/43626e2052fcdd8ee06e0164911fbe534db1ced9 plus some minor logging improvements.
Signed-by: Petr Štetiar \<ynezz@true.cz\>
> Fixes and improvements

- LICENSE
Add licenses from strlcpy & libjson
> Maintain license file

- conf/functions.in
- doc/chilli.conf
- doc/chilli.conf.5.in
> Remove www.coova.org from the uamallowed list

- src/kcoova.c
This updates a user's byte/packet counts in layer3 mode so radius messages are accurate and users are logged out when limits are reached.
> Add layer3 support to kmod_coova_sync

- src/net.c
Missing %zu format for size_t field
> size_t data wants %zu format string

- src/main-proxy.c
- src/main-radsec.c
- src/radius.c
- src/radius.h
Refactored some duplicated radius sendto() calls.
> refactor radius packet send function

- ChangeLog
- configure.ac
Bump version
modified:   ChangeLog
> Populate ChangeLog with changes since v1.3.1.4

- README.md
Mention that the issues section on Github is for bug reports.
modified:   README.md
> Link to new mailing lists for discussion & announcements

- src/chilli.c
We needed packet counts in a condown script
> export input_packets and output_packets for scripts to use

- src/chilli.c
- src/cmdsock.c
- src/conn.c
- src/dhcp.c
- src/dns.c
- src/ewt.c
- src/garden.c
- src/location.c
- src/redir.c
- src/ssl.c
- src/statusfile.c
This is a patch to add the function name and the line number into the
syslog messages, for debug purpose.
Not all messages are modified, and only messages with LOG_DEBUG severity.
> Add function name and line number into syslog.

- src/chilli.c
> Fix chilli.c check if the flag MF is set or not

- src/dhcp.c
> Fix answer buffer size to avoid chilli crash.

- miniportal/config-local.sh.in
- www/chilliform.chi.sh
- www/chillijs.chi.sh
- www/config.sh.in
- www/wwwsh
It is not a requirement & creates new problems for users in resource
constrained platforms.
> Revert commit to use bash by scripts.

- INSTALL
With instructions relevant to coova-chilli. To go from checkout to building a minimal coova instance with miniportal. (work in progress)
> Replace INSTALL document

- conf/chilli.in
ifconfig is deprecated on some distribution (tested on debian 9)
ip replace it
> Change ifconfig to ip

- configure.ac
- src/ippool.c
- src/md5.h
- src/ssl.c
- src/ssl.h
Patch taken from OpenWrt.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
> Fix compilation with newer wolfSSL
