- src/md5.c
- src/md5.h
You will need recompile CyaSSL library with --enable-opensslextra compile option.
> Fix compile error with --with-cyassl compile option

- src/radius.c
Printing to stdin makes no sense, and always produces an error from safe_write.
> Print RADIUS queue to fd 2

- src/chilli.c
- src/chilli.h
- src/conn.c
- src/dhcp.c
- src/dns.c
- src/garden.c
- src/main-opt.c
- src/main-proxy.c
- src/main-redir.c
- src/mssl.c
- src/net.c
- src/redir.c
- src/safe.c
- src/ssl.c
- src/tun.c
Too many C files forgot to include debug.h, which resulted in `_debug_` never to be `#define`d, and many debug statements to do nothing.
> #include debug.h from system.h

- src/Makefile.am
This should be left to the configure script. This makes sane debugging of chilli possible by allowing compilation without optimisation.
> Do not force -O2 compilation

- src/radius.c
The packet length was not taking the extra VSA-structure into account when checking for packet size overflow.
This fixes #40.
> Fix packet length check when adding VSAs

- .gitignore
This tells git about temporary files generated when building Debian packages.
> Ignore debian packaging temp files

- debian/rules
Pass CFLAGS to configure so they are picked up correctly, and skip the dh_strip call if `nostrip` is requested.
> Fix debian build options

- configure.ac
this fixes bootstrapping on OpenBSD which broke after the removal of files which were regenerated during this process.
> Use the AM_PROG_CC_C_O macro

- configure.ac
- extern/strlcpy.c
- src/Makefile.am
- src/chilli.c
- src/chilli.h
- src/dhcp.c
- src/garden.c
- src/main-opt.c
- src/main-proxy.c
- src/main-query.c
- src/main-radconfig.c
- src/main-redir.c
- src/main-response.c
- src/net.c
- src/radius.c
- src/redir.c
- src/rtmon.c
- src/ssl.c
- src/system.h
- src/tun.c
- src/util.c
Use a tried and tested function commonly found on modern operating systems. Include the implementation to use on systems which do not ship with it as standard.
Signed-by: Sevan Janiyan <venture37@geeklan.co.uk>
> Switch from safe_strncpy() to strlcpy()

- bstring/bstraux.c
- bstring/snprintf.c
- json/debug.c
- json/linkhash.c
- json/printbuf.c
- src/chilli.c
- src/dhcp.c
- src/queue.c
- src/redir.c
- src/ssl.c
This PR fixes the following issues:
* Dead code removed (file `bstring/bstraux.c`).
* `va_end` method not called after `va_start` call.
* File descriptor not closed (files `src/redir.c` and `src/chilli.c`).
* `openssl_free` not called (file `src/ssl.c`).
* Incorrect data type in (file `src/queue.c`).
The project is correctly built after these changes (with almost all options enabled).
free free to report me any comment. I will update and squash this PR if needed.
> Bugs and memory leaks fixed

- conf/defaults.in
- conf/up.sh.in
- configure.ac
- src/dhcp.c
added a config variable called HS_UDP_PORTS with similar functionality as HS_TCP_PORTS.
I thought it may be useful for protocols like l2tp that need to create a tunnel to the device.
> add support for extra udp ports in the iptables rules

- src/dns.c
Var not used if the _debug_ is not defined. 
Fix for issue #101
> Unused variable when _debug_ is not active

- src/garden.h
- src/main-proxy.c
- src/redir.h
Signed one-bit fields can have 0 or -1 values, unsigned one-bit fields can be 0 or 1.
> Change one-bit fields from signed to unsigned.

- conf/up.sh.in
I moved the drop rule to use insert instead of append because it fails to do the job if the system previously has other rules in the INPUT table that are not related to the coova interface. For example in my case the append rule lands after:
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT 
and this allows the hotspot client access to my ssh port, even though the port is not in HS_TCP_PORTS.
> fix order of iptables rules

- src/safe.c
> Remove the implementation of fork() which was missed through the rename.

- src/system.h
Host would have a better idea what endian it is.
inttypes.h is needed for PRIu64
Don't undefine __STRICT_ANSI__
Tested on OpenBSD, OS X El Capitan, Alpine Linux (musl libc) on armv7l
modified:   src/system.h
> Remove hacks

- configure.ac
AC_C_CONST is needed at present
> Unbreak configure on Debian 8

- src/rtmon.c
in Ubuntu this code failed to compile
```
rtmon.c:61:21: error: format '%p' expects argument of type 'void *', but argument 3 has type 'int' [-Werror=format=]
syslog(LOG_ERR, "Binding on socket(%p) failed.", sock);
```
> fix compilation error in ubuntu

- src/dhcp.c
- src/dns.c
- src/redir.c
- src/tun.c
I tried building with debug2 on a 64 bit machine and it kept stopping with messages like '%d expects int, but argument is size_t'
> fix size_t prints in debug messages for 64bit platforms

- src/chilli.c
- src/cmdsock.c
- src/garden.c
- src/main-opt.c
- src/main-query.c
- src/main-redir.c
- src/sample-mod.c
While the previously used calls to safe_strcpy() were switched to strlcpy(), there were some calls to strcpy() which were left unconverted.
> Switch calls from strcpy(3) to strlcpy(3)

- configure.ac
From the autoconf docs:
"This macro is intended for use by Gnulib (see Gnulib) and other packages that
supply a substitute stdbool.h on platforms lacking a conforming one."
Macro introduced via autoupdate, flagged an error in travis build output as
macro is not available there.
> Remove the AC_CHECK_HEADER_STDBOOL macro as it is redundant.

- src/chilli.c
Fix error issue #167 :
```C
chilli.c: In function 'chilli_learn_location':
chilli.c:2964:9: error: 's_state' undeclared (first use in this
function)
sizeof(s_state.pending_location));
```
s_state is declared in the appconn.
```C
sizeof(appconn->s_state.pending_location);
```
Signed-off-by: Baligh GUESMI gasmibal@gmail.com
> Fix compile error with --enable-location

- src/radius.c
- src/redir.c
It's a fix for a bug I've introduced in b7190800b. Using fd/stream after
close/fclose is not a good idea, at least not much helpful for debugging
as fileno() would return always -1 on the invalid stream.
Thanks to Sevan for noticing it.
Signed-off-by: Petr Štetiar <ynezz@true.cz>
> radius/redir: Fix usage of already closed fd and stream used in logging

- src/net.c
Reopening the socket will cause incoming packets to be dropped and can
cause a flood of read errors spamming the logging facility and creating
a high peak in the load.
Signed-off-by: Benjamin Berg <benjamin@sipsolutions.net>
Signed-off-by: René van Weert <r.vanweert@sowifi.com>
> Do not reopen the socket just because writing would block.

- acsite.m4
- configure.ac
Bump AC_PREREQ to 2.59 (the earliest version I could find to reference
AC_CONFIG_HEADERS)
modified:   acsite.m4
> Replace obsolete macros with current equivalents.

- conf/functions.in
Point out by @wlanmac in sevan/coova-chilli@62ab76bdcc
> Remove redundant reference to HS_UAMSERVER

- conf/functions.in
on daemon start I get: 
Starting chilli: /etc/chilli/functions: line 77: # THIS FILE IS AUTOMATICALLY GENERATED
cmdsocket       $CMDSOCK
unixipc         $IPCFILE
pidfile         $PIDFILE
net             $HS_NETWORK/$HS_NETMASK
uamlisten       $HS_UAMLISTEN
uamport         $HS_UAMPORT
dhcpif          $HS_LANIF
uamallowed      "${$HS_UAMSERVER}$webadmin$uamallow"
uamanydns
$(cat $configs1)
$HS_RAW_CONFIG1
: bad substitution
> fix bad substitution error message when parsing functions file

- doc/chilli.conf.5.in
- src/cmdline.ggo
- src/main-opt.c
- src/options.c
- src/options.h
- src/ssl.c
This patch:
* Disables SSLv2 and SSLv3 since they are no more secure (like POODLE, DROWN, etc).
* Allow explicitly specify SSL ciphers (like apache and other do) via sslciphers configuration option. This enable users to exclude some low ciphers if they want.
> Disable SSLv2 and SSLv3 protocol. Add sslciphers option

- src/chilli.c
When coova-chilli is about to exit, it release all app_conn_t object. But do not update references handled by dhcp_conn_t object.
When creating the binary status file, a garbage app_conn_t object will be stored associated to the dhcp_conn_t object.
This FIX is just about updating the references whithin dhcp_conn_t objects. Will fix #195 too.
Signed-off-by: Baligh GUESMI
> FIX error in loading binary status file.

- src/dhcp.c
The Sequence number in a response must be the Acknowledgment number from the request.
> FIX Sequence number in the TCP RESET.

- acsite.m4
The function-name being defined by an AC_DEFUN needs to be quoted with square brackets.
> Fix AC_DEFUN call more compliant with modern autoconf

- src/radius.c
"radius" is a global variable. "this" is more appropriate.
> radius: use this instead global radius

- src/ippool.c
I find it useful to know what the out of range address is.  Helps me track it down.
> Include address when complaining about static out of range

- src/chilli.c
- src/linux/Makefile
- src/redir.c
This pull request fixes bunch of build error that were encountered while building coova-chilli on fedora 24 with kernel 4.7.2 and GCC-6.0. These errors were due usage of non-standard kernel/uapi header while building the ip_coova module and misleading indentation used in the coova-chilli source that was flagged by gcc6 newly introduced -Wmisleading-indentation warning.
> Fix build failures with ipt_coova kernel module and coova-chilli source

- .travis.yml
- configure.ac
- src/Makefile.am
This fixes a build error that occurs when --enable-json config flag is
set and libjson-c is not available. This adds a check in configure.ac
for availability of libjson-c library.
Also libjson-c was not present in the list of linked libraries for chilli
binary. Hence a linker error complaining about missing json_object_xxx
functions used to occur. To fix this a new m4 macro named LIBJSON is
added to configure.ac that expands to -ljson-c and is added to list of
libraries to be linked to chill in src/Makefile.am.
Signed-off-by: Vaibhav Jain <vaibhav@linux.vnet.ibm.com>
> chilli: Fix a build error with --enable-json

- src/chilli.c
according to https://tools.ietf.org/html/rfc2865, section 5.1, the User-Name attribute may be sent in an Access-Accept packet the client should use the given username for the accounting session that follows.
I came across this in the context of a scenario where a wifi user is moving from one access point to another and I need to avoid re-authentication. So I configured coova to do macauth and the radius server will search for an open session for the client MAC and return the real authenticated username in the Access-Accept packet. The client will start a new accounting session, but it will still be tracked with the real username and thus, the account restrictions will apply.
> add override of username if received in an Access-Accept packet

- src/chilli.c
- src/chilli.h
- src/main-opt.c
- src/options.c
- src/options.h
- src/radius.c
- src/session.h
Previously, --enable-location was dependant on --enable-proxyvsa, i.e. it
used fields/functions ifdef-ed away on ENABLE_PROXYVSA
This patch replaces most of them by
"#if defined(ENABLE_LOCATION) || defined(ENABLE_PROXYVSA)"
Since I don't use proxyvsa (mostly because of issue #262 ), I don't know
if proxyvsa needs alls these fields, or if they could be guarded by
"#ifdef ENABLE_LOCATION"
Also I only tested this with proxyloc=32 (NASIdentifier) on a cisco-AP,
which is a non-VSA. Tracking location with a VSA might eventually not work.
Signed-off-by: Tim Riemenschneider <git@tim-riemenschneider.de>
> Allow --enable-location without --enable-proxyvsa

- src/system.h
ethernet.h contents defined in linux/if_ether.h
fixes #291
> Built with 4.4.14 fails

- src/chilli.c
This fix is about removing redundant lin inthe clear_appcon() function.
> Remove redundant line.

- src/redir.c
This fix is about parsing properly the GET tag when a HTTPS proxy is
used by the browser.
> Fixe browsers using a HTTPS proxy behind coova.

- src/chilli.c
This patch is about Syslog. When applied, coova-chilli will use the
filename as Syslog identity.
This is an enhancement, to be able to launch 2 instances of the daemon
with different Syslog identities.
For issue #275, we could use a symbolic links to the real filename and
execute coova-chilli using those links.
This is better than adding a new option to the already long list !
> Ability to configure the Syslog Identity

- src/ssl.c
This patch is about passphrase support in the openssl, which is contain
a problem in the password callback return value. This function must
return the length of the password to the calling function.
Thanks to @miglio
> Fix sslkeypass not working #297

- src/chilli.c
by casting to long long int. On operating systems which only support 32-bit time this should be a
noop.
Tested on a 1st gen Raspberry Pi with Raspbian, NetBSD-HEAD i386 &
OpenBSD-current i386.
> Deal with the differing levels of support for 64 bit time_t 

- src/ms_chap.c
The original des_ prefixed functions were renamed to use a DES_prefix in OpenSSL 0.9.7.
This enables linking against modern OpenSSL forks such as LibreSSL.
> Switch from des_ to DES_ prefix functions.

- src/net.c
setsockopt() with TCP_NODELAY incorrectly used SOL_SOCKET protocol level
which lead to setting SO_DEBUG. Changed level to IPPROTO_TCP.
Pull request for issue #357.
> Incorrect usage of setsockopt TCP_NODELAY

- src/net.c
This fix is about adding support to set TCP_NODELAY option into socket,
but only when the socket type is really a stream compatible.
> Fix TCP_NODELAY error.

- src/chilli.c
Syslog message is conditionned by the `_option.debug` flags.
We want all error message to be sent to syslog with not matter of the
Debug state flag.
> Error Log set by debug option.

- src/net.c
Remove setsockopt() call.
The socket is always created as SOCK_RAW, and the only (commented-out)
alternative is SOCK_DGRAM. Neither can have TCP_NODELAY aplied.
> setsockopt failed after last commit #368

- conf/chilli.in
Tell daemon helper not to parse any more options.
Fixes #416
> Fix init script

- src/garden.c
Fix following error at build time:
garden.c: In function ‘garden_print_appconn’:
garden.c:77:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
if (!safe_write(fd, line, strlen(line))) /* error */;
^~
garden.c:83:7: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
garden_print_list(fd,
^~~~~~~~~~~~~~~~~
Fixes #413
> Fix build with ENABLE_SESSGARDEN but not HAVE_PATRICIA

- src/radius.c
- src/radius.h
The RADIUS proxy feature was broken because the response to the authenticator was sent through the RADIUS server socket (`(struct radius_t)::fd` instead of `(struct radius_t)::proxyfd`).
This bug was introduced in #236 (bfe0e4b024735482b2db6cd67e0c4d57cf38b9b3).
> Fix RADIUS proxy feature (wrong reply socket)

- src/main-redir.c
- src/options.c
musl lacks `allocated` member on `struct re_pattern_buffer` (`regex_t`)
(https://fossies.org/dox/musl-1.1.20/structre__pattern__buffer.html).
Patch inspired by @drkhosla's comment at issue https://github.com/coova/coova-chilli/issues/200#issuecomment-253497070
> fix compilation with --enable-chilliredir and musl

- src/dhcp.c
The macro redir_memcopy expands to multiple statements. However, one of
if-blocks where it is used lacks braces for the code block. This results
in parts of the macro being executed even if not intended and triggers
a compiler warning on modern GCC versions.
> Fix session handling on DHCP NAK packets

- src/redir.c
The macro redir_memcopy expands to multiple statements. However, one of
if-blocks where it is used lacks braces for the code block. This results
in parts of the macro being executed even if not intended and triggers
a compiler warning on modern GCC versions.
> Fix macro expansion bug

- src/ssl.c
- src/ssl.h
Initialization and Deinitialization is deprecated and does nothing.
HAVE_OPENSSL_ENGINE is totally broken since OpenSSL 1.1 since the header
is always available. Use the normal Openssl define.
Added missing err.h header that was implicitly included.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
> Fix compilation without deprecated OpenSSL APIs

- src/system.h
<linux/netlink.h> includes <linux/sysinfo.h> , which redefines struct sysinfo, leading to an error.
Define the linux header as included to solve compilation.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
> system.h: Fix compilation with kernel 4.19 + musl

- bstring/bstrlib.c
There is a small typo in bstring/bstrlib.c.
Should read `tightest` rather than `tighest`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, tighest -> tightest

- src/chilli.c
The nousergardendata in the options struct is only defined if garden
accounting is also enabled.
> chilli: fix build with --enable-authedallowed

- src/dns.c
`dns.c:139:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]`
> src/dns.c: fix misleading indentation warning
